<template>
  <div>
    <md-table v-model="users" :table-header-color="tableHeaderColor">
      <md-table-row slot="md-table-row" slot-scope="{ item }">
        <md-table-cell md-label="Nombre">{{ item.MATERIAL }}</md-table-cell>
        <md-table-cell md-label="Descripcion">{{
          item.DESCRIPCION
        }}</md-table-cell>
        <md-table-cell md-label="Proveedor">{{ item.PROVEEDOR }}</md-table-cell>
        <md-table-cell md-label="Clase">{{ item.CLASE }}</md-table-cell>
      </md-table-row>
    </md-table>
  </div>
</template>

<script>
export default {
  name: "resina-table",
  props: {
    tableHeaderColor: {
      type: String,
      default: "",
    },
  },
  data() {
    return {
      selected: [],
      users: [
        {
          MATERIAL: "CR022411-0081-I",
          DESCRIPCION: "AKULON M-2360/HS, GRAY GY8728, A",
          PROVEEDOR: "DSM",
          CLASE: "A",
        },
        {
          MATERIAL: "CR022411-0156-I",
          DESCRIPCION: "AKULON M-2360/HS, BLACK BK9034, A",
          PROVEEDOR: "DSM",
          CLASE: "A",
        },
        {
          MATERIAL: "CR024611-0177-I",
          DESCRIPCION: "AKULON M-2408, BLACK BK9035, A",
          PROVEEDOR: "DSM",
          CLASE: "A",
        },
        {
          MATERIAL: "CR025111-0218-I",
          DESCRIPCION: "DIMS1-100-42",
          PROVEEDOR: "",
          CLASE: "",
        },
        {
          MATERIAL: "CR025111-0233-I",
          DESCRIPCION: "STANYL TE210F2, BLACK BK, A",
          PROVEEDOR: "DSM",
          CLASE: "A",
        },
        {
          MATERIAL: "CR023211-0105-I",
          DESCRIPCION: "AKULON M-2408, GRAY GY9080, A",
          PROVEEDOR: "DSM",
          CLASE: "A",
        },
        {
          MATERIAL: "CR024611-0165-I",
          DESCRIPCION: "AKULON M-2408, GREEN GN62201, A",
          PROVEEDOR: "DSM",
          CLASE: "A",
        },
        {
          MATERIAL: "CR022411-0140-I",
          DESCRIPCION: "AKULON M-2360/HS, GREEN GN62200, A",
          PROVEEDOR: "DSM",
          CLASE: "A",
        },
        {
          MATERIAL: "CR026311-0230-I",
          DESCRIPCION: "ARNITEL UM551-V, ORANGE OR45401, A",
          PROVEEDOR: "DSM",
          CLASE: "A",
        },
        {
          MATERIAL: "CR022111-0247-I",
          DESCRIPCION: "CELANEX 3316, RED ES4511, A",
          PROVEEDOR: "TICONA",
          CLASE: "B",
        },
        {
          MATERIAL: "CR022111-0249-I",
          DESCRIPCION: "DIMS1-100-80 TICONA CELANEX 3316 ED3002",
          PROVEEDOR: "",
          CLASE: "",
        },
        {
          MATERIAL: "CR025111-0235-I",
          DESCRIPCION: "STANYL TE210F2, BROWN BN48100, A",
          PROVEEDOR: "DSM",
          CLASE: "C",
        },
        {
          MATERIAL: "CR024211-0158-I",
          DESCRIPCION: "AKULON M-2360/HS, BROWN BN9031, A",
          PROVEEDOR: "DSM",
          CLASE: "B",
        },
        {
          MATERIAL: "CR024611-0180-I",
          DESCRIPCION: "AKULON M-2408, BLUE BL9213, A",
          PROVEEDOR: "DSM",
          CLASE: "A",
        },
        {
          MATERIAL: "CR023411-0201-I",
          DESCRIPCION: "VALOX420RGY",
          PROVEEDOR: "",
          CLASE: "",
        },
        {
          MATERIAL: "CR023411-0202-I",
          DESCRIPCION: "VALOX420RBK",
          PROVEEDOR: "",
          CLASE: "",
        },
        {
          MATERIAL: "CR023411-0203-I",
          DESCRIPCION: "VALOX420RGN",
          PROVEEDOR: "",
          CLASE: "",
        },
        {
          MATERIAL: "702928-1",
          DESCRIPCION: "ULTEM 2300, BLACK 7301, A",
          PROVEEDOR: "SABIC",
          CLASE: "A",
        },
        {
          MATERIAL: "CR024811-0175-I",
          DESCRIPCION: "ULT1010R-7101",
          PROVEEDOR: "",
          CLASE: "",
        },
        {
          MATERIAL: "021811-0174-I",
          DESCRIPCION: "RYTON R-4-02XT, BLACK BL, A",
          PROVEEDOR: "SOLVAY SPECIALTY",
          CLASE: "A",
        },
        {
          MATERIAL: "CR026511-0245-I",
          DESCRIPCION: "DIMS1-100-84",
          PROVEEDOR: "",
          CLASE: "",
        },
        {
          MATERIAL: "CR022111-0246-I",
          DESCRIPCION: "CELANEX 3316, YELLOW EL4111, A",
          PROVEEDOR: "TICONA",
          CLASE: "C",
        },
        {
          MATERIAL: "CR025111-0232-I",
          DESCRIPCION: "STANYL TE210F2, GRAY GY70005, A",
          PROVEEDOR: "DSM",
          CLASE: "B",
        },
        {
          MATERIAL: "CR025111-0182-I",
          DESCRIPCION: "STANYL TE250F9, BLACK BK, A",
          PROVEEDOR: "DSM",
          CLASE: "C",
        },
        {
          MATERIAL: "2136606-1",
          DESCRIPCION: "ARNITE TV4 261 T, NATURAL, A",
          PROVEEDOR: "DSM",
          CLASE: "C",
        },
        {
          MATERIAL: "702711-2",
          DESCRIPCION: "ULTEM 1000, BLACK 7101, A",
          PROVEEDOR: "",
          CLASE: "C",
        },
        {
          MATERIAL: "3-1573497-6",
          DESCRIPCION: "COLORANT, TERRA BROWN NB83620073, A",
          PROVEEDOR: "CLARIANT",
          CLASE: "C",
        },
        {
          MATERIAL: "704067-2",
          DESCRIPCION: "PBT COLORANT, GRAY NB7SAD, A",
          PROVEEDOR: "CHASE PLASTIC",
          CLASE: "C",
        },
        {
          MATERIAL: "704067-5",
          DESCRIPCION: "PBT COLORANT, GREEN NB6SAD, A",
          PROVEEDOR: "CLARIANT",
          CLASE: "C",
        },
        {
          MATERIAL: "704067-3",
          DESCRIPCION: "COLORANT PBT, BLACK NB9UFB, A",
          PROVEEDOR: "CLARIANT",
          CLASE: "C",
        },
        {
          MATERIAL: "2-703980-0",
          DESCRIPCION: "COLORANT, YELLOW 960-179, A",
          PROVEEDOR: "TEKNOR",
          CLASE: "C",
        },
        {
          MATERIAL: "3-1573497-7",
          DESCRIPCION: "PBT COLORANT, RED ORANGE NB23620047, A",
          PROVEEDOR: "CLARIANT",
          CLASE: "C",
        },
        {
          MATERIAL: "1573397-1",
          DESCRIPCION: "ULTRADUR B4300G6 HS, BLACK LS 15045, A",
          PROVEEDOR: "BASF MEXICANA",
          CLASE: "C",
        },
        {
          MATERIAL: "1573692-2",
          DESCRIPCION: "VYDYNE R533H, BLACK BK02, A",
          PROVEEDOR: "",
          CLASE: "C",
        },
        {
          MATERIAL: "703855-2",
          DESCRIPCION: "CELANEX 3316, BLACK ED3002, A",
          PROVEEDOR: "TICONA",
          CLASE: "A",
        },
        {
          MATERIAL: "703570-1",
          DESCRIPCION: "STANYL TE250F6, BLACK, A",
          PROVEEDOR: "DSM",
          CLASE: "A",
        },
        {
          MATERIAL: "1-704734-6",
          DESCRIPCION: "ULTRADUR B4300G3, RED RD45075, A",
          PROVEEDOR: "BASF MEXICANA",
          CLASE: "C",
        },
        {
          MATERIAL: "1573396-1",
          DESCRIPCION: "ULTRADUR B4300G4 HS, BLACK LS 15045, A",
          PROVEEDOR: "BASF MEXICANA",
          CLASE: "C",
        },
        {
          MATERIAL: "703194-1",
          DESCRIPCION: "VALOX 508, BLACK 7001/1066, A",
          PROVEEDOR: "SABIC",
          CLASE: "C",
        },
        {
          MATERIAL: "703307-2",
          DESCRIPCION: "FORTRON 1140L4, BLACK SD3002, A",
          PROVEEDOR: "TICONA",
          CLASE: "C",
        },
        {
          MATERIAL: "703566-2",
          DESCRIPCION: "VALOX 508R, BLACK BK1066, A",
          PROVEEDOR: "SABIC",
          CLASE: "C",
        },
        {
          MATERIAL: "1573394-1",
          DESCRIPCION: "ULTRADUR B4300G2 HS, BLACK LS 15045, A",
          PROVEEDOR: "BASF MEXICANA",
          CLASE: "C",
        },
        {
          MATERIAL: "18390-5",
          DESCRIPCION: "VALOX 325, BLACK BK1066/7001, A",
          PROVEEDOR: "SABIC",
          CLASE: "C",
        },
        {
          MATERIAL: "CR022411-0197-I",
          DESCRIPCION: "AKULON M-2360/HS, BLACK BK9034, G",
          PROVEEDOR: "",
          CLASE: "",
        },
        {
          MATERIAL: "CR022411-0106-I",
          DESCRIPCION: "AKULON M-2360/HS, GRAY GY8728, G",
          PROVEEDOR: "",
          CLASE: "",
        },
        {
          MATERIAL: "2136272-1",
          DESCRIPCION: "DIC-PPS Z-240-DS, BLACK, A",
          PROVEEDOR: "DIC INTERNATIONAL",
          CLASE: "C",
        },
        {
          MATERIAL: "704371-8",
          DESCRIPCION: "CELANEX 2002-2, BLACK ED3002",
          PROVEEDOR: "TICONA",
          CLASE: "C",
        },
        {
          MATERIAL: "1573755-1",
          DESCRIPCION: "VALOX 420SE0, BLACK BK1066/7001, A",
          PROVEEDOR: "SABIC",
          CLASE: "A",
        },
        {
          MATERIAL: "704734-1",
          DESCRIPCION: "ULTRADUR B4300G3, BLACK BK5110, A",
          PROVEEDOR: "BASF MEXICANA",
          CLASE: "C",
        },
        {
          MATERIAL: "704734-4",
          DESCRIPCION: "ULTRADUR B4300G3, NATURAL (UNCOLORED), A",
          PROVEEDOR: "BASF MEXICANA",
          CLASE: "C",
        },
        {
          MATERIAL: "703554-2",
          DESCRIPCION: "STANYL TE200F6, BLACK,  A",
          PROVEEDOR: "DSM",
          CLASE: "C",
        },
        {
          MATERIAL: "1-704734-9",
          DESCRIPCION: "ULTRADUR B4300G3, YELLOW YW55080, A",
          PROVEEDOR: "BASF CORP",
          CLASE: "C",
        },
        {
          MATERIAL: "1573397-2",
          DESCRIPCION: "ULTRADUR B4300G6 HS, NATURAL, A",
          PROVEEDOR: "BASF CORP",
          CLASE: "C",
        },
        {
          MATERIAL: "702998-8",
          DESCRIPCION: "PE COLORANT, ZINC YELLOW 2/7340, A",
          PROVEEDOR: "CLARIANT",
          CLASE: "C",
        },
        {
          MATERIAL: "704067-4",
          DESCRIPCION: "COLORANT, REED FOR PBT, ORANGE NB2SAD, A",
          PROVEEDOR: "NEW CONCEPT",
          CLASE: "C",
        },
        {
          MATERIAL: "3-704618-1",
          DESCRIPCION: "PBT COLORANT, SIGNAL BLUE NB53620012, A",
          PROVEEDOR: "CHASE PLASTIC",
          CLASE: "C",
        },
        {
          MATERIAL: "1573472-2",
          DESCRIPCION: "ULTRADUR B4300G3 HS, BLACK LS 15045, A",
          PROVEEDOR: "BASF CORP",
          CLASE: "C",
        },
        {
          MATERIAL: "704987-1",
          DESCRIPCION: "ULTEM 1010R, BLACK 7101, A",
          PROVEEDOR: "SABIC",
          CLASE: "A",
        },
        {
          MATERIAL: "703329-2",
          DESCRIPCION: "CRASTIN T843 FR NAT A",
          PROVEEDOR: "DUPONT",
          CLASE: "C",
        },
        {
          MATERIAL: "703593-4",
          DESCRIPCION: "ULTRAMID A3XZG5, NATURAL/UNCOLORED, A",
          PROVEEDOR: "BASF CORP",
          CLASE: "C",
        },
        {
          MATERIAL: "703395-1",
          DESCRIPCION: "CELANEX 4300, BLACK ED-3002, A",
          PROVEEDOR: "TICONA",
          CLASE: "C",
        },
        {
          MATERIAL: "1573755-6",
          DESCRIPCION: "VALOX 420SE0, NATURAL 1001, A",
          PROVEEDOR: "SABIC",
          CLASE: "C",
        },
        {
          MATERIAL: "18618-2",
          DESCRIPCION: "POCAN B-3225, NATURAL 000000, A",
          PROVEEDOR: "LANXESS",
          CLASE: "A",
        },
        {
          MATERIAL: "1-703197-4",
          DESCRIPCION: "VALOX 357M, GRAY 8051, A",
          PROVEEDOR: "SABIC",
          CLASE: "C",
        },
        {
          MATERIAL: "2136736-1",
          DESCRIPCION: "CELANEX 3216HR, GRAY EC4282, A",
          PROVEEDOR: "TICONA",
          CLASE: "C",
        },
        {
          MATERIAL: "2-703980-4",
          DESCRIPCION: "COLORANT, GREEN 51,117TCPAS, A",
          PROVEEDOR: "TEKNOR",
          CLASE: "C",
        },
        {
          MATERIAL: "703197-1",
          DESCRIPCION: "VALOX 357M, BLACK BK1066/7001, A",
          PROVEEDOR: "SABIC",
          CLASE: "C",
        },
        {
          MATERIAL: "702624-6",
          DESCRIPCION: "VALOX 357, RED 6187, A",
          PROVEEDOR: "SABIC",
          CLASE: "C",
        },
        {
          MATERIAL: "2-1573755-4",
          DESCRIPCION: "VALOX 420SE0, BLUE 2051, A",
          PROVEEDOR: "SABIC",
          CLASE: "C",
        },
        {
          MATERIAL: "1-703197-3",
          DESCRIPCION: "VALOX 357M, NATURAL 1001, A",
          PROVEEDOR: "SABIC",
          CLASE: "C",
        },
        {
          MATERIAL: "1-1573755-6",
          DESCRIPCION: "VALOX 420SE0, GRAY 8051, A",
          PROVEEDOR: "SABIC",
          CLASE: "C",
        },
        {
          MATERIAL: "1-703197-5",
          DESCRIPCION: "VALOX 357M, BLUE 2051, A",
          PROVEEDOR: "SABIC",
          CLASE: "C",
        },
        {
          MATERIAL: "2-703980-1",
          DESCRIPCION: "COLORANT, GRAY 960-180, A",
          PROVEEDOR: "TEKNOR",
          CLASE: "C",
        },
        {
          MATERIAL: "2136736-2",
          DESCRIPCION: "CELANEX 3216HR, NATURAL EF3001, A",
          PROVEEDOR: "TICONA",
          CLASE: "A",
        },
        {
          MATERIAL: "1-1573155-8",
          DESCRIPCION: "PBT COLORANT, DUSTY GRAY 55-9863, A",
          PROVEEDOR: "UNIFORM",
          CLASE: "C",
        },
        {
          MATERIAL: "3-704618-3",
          DESCRIPCION: "PBT COLORANT, LEAF GREEN NB64620027, A",
          PROVEEDOR: "CLARIANT",
          CLASE: "C",
        },
        {
          MATERIAL: "6-1573822-3",
          DESCRIPCION: "RENOL FOR PBT, ORANGE NB23820015, A",
          PROVEEDOR: "CLARIANT",
          CLASE: "A",
        },
        {
          MATERIAL: "6-1573822-4",
          DESCRIPCION: "RENOL FOR PBT, VIOLET NB44820015, A",
          PROVEEDOR: "CLARIANT",
          CLASE: "A",
        },
        {
          MATERIAL: "6-1573822-5",
          DESCRIPCION: "RENOL FOR PBT, BLUE NB54820037, A",
          PROVEEDOR: "CLARIANT",
          CLASE: "A",
        },
        {
          MATERIAL: "6-704402-4",
          DESCRIPCION: "COLORANT, REEDLITE, VIOLET NB4SAD, A",
          PROVEEDOR: "CLARIANT",
          CLASE: "C",
        },
        {
          MATERIAL: "6-704402-6",
          DESCRIPCION: "PBT COLORANT, TAN NB8UMC, A",
          PROVEEDOR: "CLARIANT",
          CLASE: "C",
        },
        {
          MATERIAL: "1573830-2",
          DESCRIPCION: "PA6 COLORANT, YELLOW AB13631688, A",
          PROVEEDOR: "CLARIANT",
          CLASE: "C",
        },
        {
          MATERIAL: "2136812-2",
          DESCRIPCION: "LIQUID COLOR, TRAFFIC BLUE FE53820043, A",
          PROVEEDOR: "CLARIANT",
          CLASE: "A",
        },
        {
          MATERIAL: "704402-3",
          DESCRIPCION: "PBT COLORANT, GRAY NB73766000, A",
          PROVEEDOR: "CLARIANT",
          CLASE: "C",
        },
        {
          MATERIAL: "8-704402-2",
          DESCRIPCION: "PBT COLORANT, BROWN NB8SAD, A",
          PROVEEDOR: "CLARIANT",
          CLASE: "C",
        },
        {
          MATERIAL: "CR025611-0222-I",
          DESCRIPCION: "AKULON R622-RS1U, BLACK BK9035, A",
          PROVEEDOR: "DSM",
          CLASE: "A",
        },
        {
          MATERIAL: "1573457-2",
          DESCRIPCION: "RYTON XK2340, BLACK, A",
          PROVEEDOR: "SOLVAY SPECIALTY",
          CLASE: "A",
        },
        {
          MATERIAL: "703653-1",
          DESCRIPCION: "ULTRADUR B4300G4, BLACK 5110, A",
          PROVEEDOR: "BASF MEXICANA",
          CLASE: "A",
        },
        {
          MATERIAL: "6-1573822-8",
          DESCRIPCION: "PBT COLORANT, DUSTY GRAY NB73820066, A",
          PROVEEDOR: "CLARIANT",
          CLASE: "A",
        },
        {
          MATERIAL: "703653-2",
          DESCRIPCION: "ULTRADUR B4300G4, NATURAL, A",
          PROVEEDOR: "BASF CORP",
          CLASE: "A",
        },
        {
          MATERIAL: "704791-2",
          DESCRIPCION: "ULTRAMID A3WG5, BLACK 564, A",
          PROVEEDOR: "BASF CORP",
          CLASE: "C",
        },
        {
          MATERIAL: "2136889-1",
          DESCRIPCION: "AKULON S223-KGS3, GRAY GY8728, A",
          PROVEEDOR: "",
          CLASE: "A",
        },
        {
          MATERIAL: "703855-5",
          DESCRIPCION: "CELANEX 3316, NATURAL EF3022, A",
          PROVEEDOR: "",
          CLASE: "C",
        },
        {
          MATERIAL: "1915284-1",
          DESCRIPCION: "HOT MELT, TECHNOMELT PA 6208, BLACK",
          PROVEEDOR: "",
          CLASE: "C",
        },
        {
          MATERIAL: "2-1573809-0",
          DESCRIPCION: "MASTERBATCH FOR PBT, GREEN NB63820016, A",
          PROVEEDOR: "",
          CLASE: "A",
        },
        {
          MATERIAL: "6-1573822-6",
          DESCRIPCION: "RENOL FOR PBT, BROWN (TAN) NB82820029, A",
          PROVEEDOR: "",
          CLASE: "A",
        },
        {
          MATERIAL: "1573401-2",
          DESCRIPCION: "CRASTIN HR5315HF, BLACK BK503, A",
          PROVEEDOR: "",
          CLASE: "A",
        },
        {
          MATERIAL: "1915284-1",
          DESCRIPCION: "HOT MELT, TECHNOMELT PA 6208, BLACK",
          PROVEEDOR: "",
          CLASE: "C",
        },
        {
          MATERIAL: "2-1573809-0",
          DESCRIPCION: "MASTERBATCH FOR PBT, GREEN NB63820016, A",
          PROVEEDOR: "",
          CLASE: "A",
        },
        {
          MATERIAL: "6-1573822-6",
          DESCRIPCION: "RENOL FOR PBT, BROWN (TAN) NB82820029, A",
          PROVEEDOR: "",
          CLASE: "A",
        },
        {
          MATERIAL: "702661-8",
          DESCRIPCION: "ULTRAMID A3EG7, IRON GRAY GR22930, A",
          PROVEEDOR: "",
          CLASE: "C",
        },
        {
          MATERIAL: "702661-9",
          DESCRIPCION: "ULTRAMID A3EG7, BLACK LS 23189, A",
          PROVEEDOR: "",
          CLASE: "C",
        },
        {
          MATERIAL: "8-1573822-9",
          DESCRIPCION: "PBT COLORANT, GRAY NB72820092, A",
          PROVEEDOR: "",
          CLASE: "C",
        },
        {
          MATERIAL: "702711-1",
          DESCRIPCION: "ULTEM 1000, NATURAL 1000, A",
          PROVEEDOR: "SABIC",
          CLASE: "C",
        },
        {
          MATERIAL: "1-1573809-9",
          DESCRIPCION: "MASTERBATCH FOR PBT, BROWN NB84820028, A",
          PROVEEDOR: "",
          CLASE: "A",
        },
        {
          MATERIAL: "2136812-4",
          DESCRIPCION: "LIQUID COLOR, LEAF GREEN FE63820053, A",
          PROVEEDOR: "",
          CLASE: "B",
        },
        {
          MATERIAL: "2136889-2",
          DESCRIPCION: "AKULON S223-KGS3, BLACK BK9034, A",
          PROVEEDOR: "",
          CLASE: "A",
        },
        {
          MATERIAL: 1053698,
          DESCRIPCION: "CELANEX 3216, BLACK, A",
          PROVEEDOR: "",
          CLASE: "C",
        },
      ],
    };
  },
};
</script>
